version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5433:5432
    volumes:
      - ~/apps/open-crowd-source-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=opencrowdsource
      - POSTGRES_DB=opencrowdsource
